# Schema for the configuration files of the Intercomm module.
intercomm.settings:
  type: config_object
  label: 'Intercomm settings'
  mapping:
    example:
      type: string
      label: 'Example'
