services:
  php:
    image: wodby/drupal-cms:$DRUPAL_CMS_TAG
#    image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - ./codebase:/var/www/html

  crond:
    image: wodby/drupal-cms:$DRUPAL_CMS_TAG
#    image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - ./codebase:/var/www/html

  mariadb:
    ports:
      - "3306:3306"
  nginx:
    volumes:
    - ./codebase:/var/www/html

#  webgrind:
#    volumes:
#    - codebase:/mnt/codebase

