ai_provider_litellm.settings:
  type: config_object
  label: 'LiteLLM AI Settings'
  mapping:
    api_key:
      type: string
      label: 'The API key for LiteLLM AI via Key module'
    moderation:
      type: boolean
      label: 'Enable moderation requests before each request.'
    host:
      type: string
      label: 'The host to use for the API requests.'
