<?php

/**
 * @file
 * Primary module hooks for Intercomm module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function intercomm_preprocess_views_view_unformatted(&$variables) {

  $view = $variables['view'];
  if ($view->id() == 'MY_VIEW' && $view->current_display == 'MY_DISPLAY') {

    $uid = \Drupal::currentUser()->id();

    $rows = $variables['rows'];
    foreach ($rows as $id => $row) {

      // Get user ID.
      $owner = $row['content']['#row']->_entity->get('uid')->target_id;

      $class = ($uid == $owner) ? 'own' : 'other';
      $custom_row_class = 'views-row-' . $class;

      $variables['rows'][$id]['attributes']->addClass($custom_row_class);
    }
  }
}